require("prototypes.damage-type")
require("prototypes.entities")
require("prototypes.items")
require("prototypes.ammo-category")
require("prototypes.ammo")
require("prototypes.recipe")
require("prototypes.tech")
require("prototypes.achievements")
